version: "3.8"

services:
  postgresdb:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=compose-postgres